---
dist: xenial
langage: python

sudo: true

env:
  - ansible_version: 2.7.16
  - ansible_version: 2.8.0
  - ansible_version: 2.8.1
  - ansible_version: 2.8.2
  - ansible_version: 2.8.3
  - ansible_version: 2.8.4
  - ansible_version: 2.8.5
  - ansible_version: 2.8.6
  - ansible_version: 2.8.7
  - ansible_version: 2.8.8
  - ansible_version: 2.9.0
  - ansible_version: 2.9.1
  - ansible_version: 2.9.2
  - ansible_version: 2.9.3

install:
  - pip install ansible==$ansible_version

script:
  - ansible-playbook playbook.yml
...
